runtime: php55
threadsafe: yes
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /([^/]+\.php)
  script: \1

- url: /.*
  script: index.php
  login: required
  secure: always

env_variables:
  MYSQL_DSN: "mysql:unix_socket=/cloudsql/apts-166316:us-central1:apts;dbname=apts_m;"
  MYSQL_USER: root
  MYSQL_PASSWORD: 345Quebec$
